# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f613af331075bdbfa045a96dcf034e5cc06c69372d1576b6f38f301aac4ae97837fc71dccf1be5579741122539ecb057103bb8bdc8a70636a50cbe44e3a450a

test:
  secret_key_base: 642d55bb6fe7f05d97d24eca8ba11dc94938a117d50159ed254a67c597de072910016611fbc55a683930af25c317239a18c1226cae43a33aab31e3228a5e9e81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
